### ISSUE TITLE
local-geocode integration

### ISSUE THREAD

**Issue by mar-muel** [crowdbreaks/streamer#1]
We have the following 4 cases (defined by `geo_type`):
0: no geolocation could be inferred
1: exact geocoordinates provided by Twitter
2: Place Polygon provided by Twitter [(longitude, latitude) refers to the centroid of the bounding box]
3: geolocation parsed from user.location field with local-geocode [in this case, geoname_id is also provided]

I think we want (at least) the following field in each case:
* geo_type
* longitude and latitude
* `location_type`
* `country_code`

The last two are given for case 3). Case 2) has two fields which could be useful: `place_type` and `country_code`. It seems like even tweets with exact locations, i.e. case 1), have a place field now, e.g. check [here](https://developer.twitter.com/en/docs/twitter-api/v1/data-dictionary/object-model/geo#tweet-exact). This means we could probably get `place_type` and `country_code` for both geo_types 1) and 2). However `place_type` does not equal to `location_type`. Maybe @francoispichard can explain how he mapped `place_type` to `location_type`.

In `preprocess` we currently use `map_data` (form naturalearthdata), but I think if we use `country_code` and `place_type` from the place object, we could probably avoid requiring this shapefile.

**Comment by francoispichard** [comment]
Hello @mar-muel, thanks for opening this issue.

> However `place_type` does not equal to `location_type`.

In order to be consistent with [line 280 of `preprocess/utils/process_tweet.py`](https://github.com/crowdbreaks/preprocess/blob/master/utils/process_tweet.py#L280),  I would phrase it slightly differently.

- There are 6 possible values for `location_type` if `geo_type == 2`: `[None, 'country', 'city', 'admin', 'poi', 'neighborhood']`
- There are 13 possible values for `location_type` if `geo_type == 3`: `[None, 'continent', 'region', 'country', 'city', 'place', 'admin1', 'admin2', 'admin3', 'admin4', 'admin5', 'admin6', 'admin_other']`

**Comment by utanashati** [comment]
> In `preprocess` we currently use `map_data` (form naturalearthdata), but I think if we use `country_code` and `place_type` from the place object, we could probably avoid requiring this shapefile.

@mar-muel As far as I understood, we use `map_data` to retrieve region and subregion. The question in terms of local-geocode integration into the pipeline then is whether it's critical to keep this info on ES, or it's enough to have `country_code` and `place_type`/`location_type`. Do we want to query ES data by region/subregion? In case we do, the map data file shouldn't be a problem, it's ~20 MB as a csv.

As I see it, in *twiprocess*, I could create a `ProcessTweetES` class that would inherit from `ProcessTweet` with `geo_info` and `extract` overridden. Or create `ProcesstweetBase` class, that both `ProcessTweet` and `ProcessTweetES` inherit from.


Also, concerning `location_type` and `place_type`. Do we want to leave them as is or do we want to map them? Like, `location_type` onto `place_type`. As François showed above, he didn't really map them, they're just two different `location_type`s.

I think, we might want to map `location_type` onto `place_type` if we want to have generalizable queries for our `location_type` field. @francoispichard, what do you think?


@francoispichard Where did you find that info about Twitter's `place_type`? I couldn't google it.

Also, don't you want to eventually move to `twiprocess.ProcessTweet` in preprocess? Cause I moved it to *twiprocess* with *preprocess* in mind, but I see that you still use and make changes to the local `ProcessTweet`.

**Comment by mar-muel** [comment]
> @mar-muel As far as I understood, we use map_data to retrieve region and subregion (country codes now being handled by Twitter in case 1). The question in terms of local-geocode integration into the pipeline then is whether it's critical to keep this info on ES, or it's enough to have country_code and place_type/location_type. Do we want to query ES data by region/subregion? In case we do, the map data file shouldn't be a problem, it's ~20 MB as a csv.

I don't think it makes sense to query by region/subregion, it just blows up the ES index size. We have the country code field, it's trivial to expand it with all country codes of a specific region using a helper function (there are also Python libraries for this).

>As I see it, in twiprocess, I could create a ProcessTweetES class that would inherit from ProcessTweet with geo_info and extract overridden. Or create ProcessTweetBase class, that both ProcessTweet and ProcessTweetES inherit from. This way, data extraction in these two may be fine-tuned for the purposes of each.

Yes, sounds good to me. Although I'm not a fan of inheritance.

>Also, concerning location_type and place_type. Do we want to leave them as is or do we want to map them? Like, location_type onto place_type. As François showed above, he didn't really map them, they're just two different location_types.

`location_type` is more expressive so we don't want to lose that information. I don't think it makes sense to do any re-mapping. I'm also not sure how we would re-map `admin`, `poi`,  and `neighborhood`. I would say, let's just merge them.

And yes, we want to move to `twiprocess` in `preprocess` eventually.

**Comment by francoispichard** [comment]
> I think, we might want to map location_type onto place_type if we want to have generalizable queries for our location_type field. @francoispichard, what do you think?

@utanashati Yes, this would make sense.

> @francoispichard Where did you find that info about Twitter's place_type? I couldn't google it.

@utanashati I found that information by returning the unique values in the column `place_type`. I went through Twitter documentation, however the most relevant page I found only shows two examples with [`'place_type' = 'city'`](https://developer.twitter.com/en/docs/twitter-api/v1/data-dictionary/object-model/geo#tweet-exact) and [`'place_type' = 'poi'`](https://developer.twitter.com/en/docs/twitter-api/v1/data-dictionary/object-model/geo#tweet-place). Nevertheless, you can find the complete list of `'place_type'` values in a [paper dropped on arXiv](https://arxiv.org/pdf/1908.10948.pdf) (_cf._ second sentence of the 2nd text column on the first page).

**Comment by utanashati** [comment]
@francoispichard Wow, thanks! A nice paper as well!

@mar-muel And what if we had another field like `location_origin` to be able to separate `location_type`s that come from Twitter's `place_type` from the ones from local-geocode?

Following this logic, we could also rename the `geo_type` field to `geo_origin`. What do you think?

**Comment by mar-muel** [comment]
Hmm I think I'd rather prefix the labels: e.g. `{geo_type}_{location_type}` for the field `location_type`. So admin from place object would be `2_admin`. admin1 form local-geocode would be `3_admin1`. What do you think?

**Comment by mar-muel** [comment]
we could also use actual keywords instead of numbers for `geo_type` in order to make it self-explanatory.

**Comment by utanashati** [comment]
Yeah, I would go for keywords in `geo_type`, but I think prefixing with `geo_type` is a bit of an overkill. It would complicate the possible queries (if the field is keyword type). I personally like the idea of having three fields: `geo-type: keyword`, `location_type: keyword`, `geocode: boolean`. This way, it should be really easy to separate the cases if needed, and adding a boolean field shouldn't significantly increase the file size.

**Comment by mar-muel** [comment]
Yes, we can keep the geocode field if you want to (although it's going to be a bit redundant since we will have
```
{
     "geo_type": "geocode",
     "geocode": true
     ...
```
But it's up to you! If you think it will make querying easier then go for it. I'm ok not doing the prefixing and just leaving the fields as is.
